from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class TaskStatus(str, Enum):
    CONFIGURING = "configuring"
    PENDING = "pending"
    ACTIVE = "active"
    COMPLETE = "complete"
    PAUSED = "paused"
    FAILED = "failed"

    @classmethod
    def _missing_(cls, value: object):
        if isinstance(value, str):
            # Normalize to lowercase before lookup
            value = value.lower()
            for member in cls:
                if member.value == value:
                    return member
        return None


class SubtaskStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"

    @classmethod
    def _missing_(cls, value: object):
        if isinstance(value, str):
            value = value.lower()
            for member in cls:
                if member.value == value:
                    return member
        return None


class SubtaskType(str, Enum):
    GENERAL = "general"
    DISCOVERY = "discovery"
    VERIFICATION = "verification"
    COMPARISON = "comparison"
    SYNTHESIS = "synthesis"

    @classmethod
    def _missing_(cls, value: object):
        if isinstance(value, str):
            value = value.lower()
            for member in cls:
                if member.value == value:
                    return member
        return None


class Subtask(BaseModel):
    """Individual subtask in a research plan"""

    model_config = ConfigDict(validate_assignment=True)

    order: int
    description: str
    success_criteria: str
    subtask_type: SubtaskType = SubtaskType.GENERAL
    status: SubtaskStatus = SubtaskStatus.PENDING
    findings: list[str] = Field(default_factory=list)


class ResearchPlan(BaseModel):
    """Research plan generated by the orchestrator"""

    model_config = ConfigDict(validate_assignment=True)

    restated_task: str
    subtasks: list[Subtask]
    current_subtask_index: int = 0
    created_at: int = Field(
        default_factory=lambda: int(datetime.now().timestamp() * 1000)
    )


class TaskMetrics(BaseModel):
    """Metrics for task execution"""

    model_config = ConfigDict(validate_assignment=True)

    searchCount: int = 0
    thinkCount: int = 0
    summaryCount: int = 0
    checkpointCount: int = 0
    webFetchCount: int = 0
    llmTokensUsed: int = 0
    errorCount: int = 0


class Task(BaseModel):
    """Main task model used across the system"""

    model_config = ConfigDict(validate_assignment=True)

    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    name: str
    description: str
    budgetMinutes: int = 180
    status: TaskStatus = TaskStatus.CONFIGURING
    progress: float = 0.0
    elapsed: int = 0
    metrics: TaskMetrics = Field(default_factory=TaskMetrics)
    research_plan: ResearchPlan | None = None
    createdAt: int = Field(
        default_factory=lambda: int(datetime.now().timestamp() * 1000)
    )
    updatedAt: int = Field(
        default_factory=lambda: int(datetime.now().timestamp() * 1000)
    )
    config: dict[str, Any] = Field(default_factory=dict)
